"""nxb-031: `nxb run`, the surface that returns an answer.

Fast on purpose: every test here drives a FAKE runtime, so the suite does not
grow another minute of real child processes. The real round trip was verified
by hand and is recorded in the task report, not run on every commit.
"""

import json
import os
import shutil
import stat
import tempfile
import unittest
from unittest import mock

from nxb import run as runmod
from nxb.adapters.claude_code import ClaudeCodeAdapter

INIT = '{"type":"system","subtype":"init","session_id":"s-run"}'


def ok_frame(task_id, summary="42", status="COMPLETE"):
    report = {"task_id": task_id, "status": status, "summary": summary,
              "files_changed": "none", "commands_run": "none",
              "evidence": "e", "risks": "none", "next_action": "none",
              "was_refused": False}
    return json.dumps({"type": "result", "subtype": "success",
                       "is_error": False, "result": json.dumps(report)})


class RunCase(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.ledger = os.path.join(self.tmp, "l.db")
        self.calls = []

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _fake(self, summary="42", status="COMPLETE"):
        outer = self

        class Fake(ClaudeCodeAdapter):
            def build_command(self, *, work_dir, prompt, out_path,
                              schema_path=None):
                outer.calls.append(prompt)
                # The task_id the worker must echo is the dispatch key, and the
                # key is generated by the surface, so the fake reads it back
                # out of the prompt rather than being told.
                tid = prompt.split("task_id MUST be exactly ")[1].split("'")[1]
                script = os.path.join(outer.tmp, f"fake{len(outer.calls)}")
                with open(script, "w") as fh:
                    fh.write("#!/bin/sh\nprintf '%s\\n%s\\n' '{}' '{}'\n".format(
                        INIT, ok_frame(tid, summary, status)))
                os.chmod(script, os.stat(script).st_mode | stat.S_IEXEC)
                return [script]
        return Fake

    def run_it(self, directive, key=None, summary="42", status="COMPLETE"):
        with mock.patch.dict(runmod.ADAPTERS,
                             {"claude_code": self._fake(summary, status)}):
            return runmod.run(directive=directive, runtime_id="claude_code",
                              ledger_path=self.ledger, dispatch_key=key,
                              drain_budget=10, out=open(os.devnull, "w"),
                              err=open(os.devnull, "w"))


class TheHumanNeverTouchesAnEnvelope(RunCase):
    def test_a_directive_and_a_runtime_are_enough(self):
        code, outcome = self.run_it("Compute something.")
        self.assertEqual(code, 0)
        self.assertEqual(outcome["report"]["summary"], "42")

    def test_the_key_and_the_digest_are_computed_not_supplied(self):
        _, outcome = self.run_it("x")
        self.assertTrue(outcome["dispatch_key"].startswith("nxb-"))

    def test_the_directive_reaches_the_worker(self):
        self.run_it("PLEASE COUNT THE SHEEP")
        self.assertIn("PLEASE COUNT THE SHEEP", self.calls[0])

    def test_a_directive_can_come_from_a_file_or_stdin(self):
        p = os.path.join(self.tmp, "d.txt")
        open(p, "w").write("from a file")
        self.assertEqual(runmod.read_directive("@" + p), "from a file")
        self.assertEqual(runmod.read_directive("literal"), "literal")


class TheSafetyPropertiesSurviveTheSurface(RunCase):
    """The three that cost this project the most to get."""

    def test_a_retry_replays_instead_of_rerunning(self):
        self.run_it("same", key="k")
        self.run_it("same", key="k")
        self.assertEqual(len(self.calls), 1, "the retry re-ran the work")

    def test_a_retry_does_not_clobber_the_answer(self):
        """nxb-031's worst defect: the retry DESTROYED what it retried for."""
        self.run_it("same", key="k")
        code, outcome = self.run_it("same", key="k")
        self.assertEqual(code, 0)
        self.assertEqual(outcome["delivery"], "REPORT_PRESENT")
        self.assertEqual(outcome["report"]["summary"], "42")

    def test_a_changed_directive_under_a_reused_key_is_REFUSED(self):
        """F1, which my first fix for the clobber silently reintroduced by
        answering from the outbox BEFORE the divergence check."""
        self.run_it("original", key="k")
        code, outcome = self.run_it("CHANGED", key="k")
        self.assertEqual(code, runmod.EXIT["REFUSED"])
        self.assertIsNone(outcome)

    def test_the_answer_survives_a_refused_divergent_retry(self):
        self.run_it("original", key="k")
        self.run_it("CHANGED", key="k")
        code, outcome = self.run_it("original", key="k")
        self.assertEqual(code, 0)
        self.assertEqual(outcome["report"]["summary"], "42")

    def test_a_relative_ledger_is_refused(self):
        with self.assertRaises(ValueError):
            runmod.run(directive="x", runtime_id="claude_code",
                       ledger_path="rel/l.db", out=open(os.devnull, "w"),
                       err=open(os.devnull, "w"))


class ExitCodesCarryState(RunCase):
    def test_a_worker_reporting_BLOCKED_does_not_exit_zero(self):
        code, outcome = self.run_it("x", status="BLOCKED")
        self.assertEqual(code, runmod.EXIT["WORKER_NOT_COMPLETE"])
        self.assertEqual(outcome["report"]["status"], "BLOCKED")

    def test_one_is_never_used_so_a_shell_cannot_merge_states(self):
        self.assertNotIn(1, runmod.EXIT.values())

    def test_an_unknown_runtime_is_named_not_raised(self):
        code, outcome = runmod.run(directive="x", runtime_id="nope",
                                   ledger_path=self.ledger,
                                   out=open(os.devnull, "w"),
                                   err=open(os.devnull, "w"))
        self.assertEqual(code, runmod.EXIT["REFUSED"])
        self.assertIsNone(outcome)


class C14(unittest.TestCase):
    """A blank id is not a start, and a blank needle matches nothing."""

    def test_a_blank_start_id_is_malformed_not_a_start(self):
        from nxb.adapters.codex import CodexAdapter
        matched, ref = CodexAdapter()._match_start(
            {"type": "thread.started", "thread_id": ""})
        self.assertTrue(matched)
        self.assertFalse(ref, "a blank ref must not read as a valid id")

    def test_evidence_for_refuses_a_blank_needle(self):
        from nxb.adapters._process import find_evidence
        from nxb.adapters.codex import CodexAdapter
        self.assertIsNone(CodexAdapter.evidence_for(""))
        self.assertIsNone(find_evidence("~", ""))
        self.assertIsNone(find_evidence("~", None))

    def test_the_contract_refuses_a_blank_runtime_ref(self):
        from nxb.h2 import h2_validate
        r = {"receipt_id": "h2-x", "hop": "H2", "parent_receipt_id": "p",
             "observed_at": "t", "observer": "o", "runtime_id": "codex",
             "runtime_ref": "", "pinned_model": "m"}
        with self.assertRaises(Exception):
            h2_validate("h2_receipt", r)


if __name__ == "__main__":
    unittest.main()
